const HTTP_UNAUTHORIZED_STATUS = 401;
const HTTP_BAD_REQUEST_STATUS = 400;
const HTTP_CREATED_STATUS = 201;
const HTTP_NO_CONTENT_STATUS = 204;
const HTTP_NOT_FOUND_STATUS = 404;
const HTTP_OK_STATUS = 200;
const PATH = './talker.json';
const PORT = '3000';

module.exports = {
    HTTP_UNAUTHORIZED_STATUS,
    HTTP_BAD_REQUEST_STATUS,
    HTTP_CREATED_STATUS,
    HTTP_NO_CONTENT_STATUS,
    HTTP_NOT_FOUND_STATUS,
    HTTP_OK_STATUS,
    PATH,
    PORT,
};